name: PR-update required Forklift pallets

scms:
  pallet:
    kind: github
    spec:
      owner: '{{ requiredEnv "REPO_OWNER" }}'
      repository: '{{ requiredEnv "REPO_NAME" }}'
      branch: edge
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      user: '{{ requiredEnv "COMMITTER_USERNAME" }}'
      email: '{{ requiredEnv "COMMITTER_EMAIL" }}'
      commitusingapi: true # this allows commits to be signed

actions:
  pull-request:
    scmid: pallet
    kind: github/pullrequest
    spec:
      title: "build(compose): bump required Forklift pallets"
      labels:
        - dependencies
      mergemethod: squash

targets:
  pallet:
    name: Update required pallets
    kind: shell
    disablesourceinput: true
    scmid: pallet
    spec:
      environments:
        - name: PATH
      command: forklift dev pallet require-pallet github.com/PlanktoScope/pallet-standard@beta
      # changedif:
      #   kind: file/checksum
      #   spec:
      #     files:
      #       - requirements/pallets/github.com/PlanktoScope/pallet-standard/forklift-version-lock.yml
