name: PR-update required Forklift pallets

scms:
  pallet:
    kind: github
    spec:
      owner: '{{ requiredEnv "REPO_OWNER" }}'
      repository: '{{ requiredEnv "REPO_NAME" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      branch: main
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      user: '{{ requiredEnv "COMMITTER_USERNAME" }}'
      email: '{{ requiredEnv "COMMITTER_EMAIL" }}'
      commitusingapi: true # this allows commits to be signed

actions:
  pull-request:
    scmid: pallet
    kind: github/pullrequest
    spec:
      title: "build(compose): bump required Forklift pallets"
      labels:
        - dependencies
      mergemethod: squash

sources:
  pallet-current:
    name: Current version of required pallet
    kind: shell
    spec:
      environments:
        - name: PATH # needed to find the forklift binary
        - name: HOME # needed for Forklift to determine its default workspace path
      command: forklift dev pallet show-pallet-version {{ .path }}

# FIXME: add a shell condition check to ensure that the version query is valid and resolved to a
# git repo which actually is a pallet, maybe by calling `forklift inspector resolve-pallet`

targets:
  pallet:
    name: Update required pallet
    kind: shell
    disablesourceinput: true
    scmid: pallet
    spec:
      environments:
        - name: PATH # needed to find the forklift binary
        - name: HOME # needed for Forklift to determine its default workspace path
      command: '{{ requiredEnv "CWD" }}/.github/forklift-require.sh pallet {{ .path }} {{ index . "version-query" }}'
