policies:
  - name: Upgrade github.com/PlanktoScope/pallet-standard
    config:
      - updatecli.d/forklift-pallets.yml
    values:
      - values.d/pallet-standard.pallet-upgrades.yml

  - name: Upgrade github.com/forklift-run/pallet-example-minimal
    config:
      - updatecli.d/forklift-pallets.yml
    values:
      - values.d/pallet-example-minimal.pallet-upgrades.yml

  - name: Upgrade github.com/forklift-run/pallet-example-overlays
    config:
      - updatecli.d/forklift-pallets.yml
    values:
      - values.d/pallet-example-overlays.pallet-upgrades.yml
