name: check

on:
  push:
    branches:
      - main
      - edge
      - beta
      - stable
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        forklift-version: [0.8.0-alpha.1]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Forklift
        uses: PlanktoScope/setup-forklift@v1
        with:
          version: ${{ matrix.forklift-version }}

      - name: Run Forklift checks
        run: forklift dev plt check

      - name: Make Forklift deployment plan
        run: forklift dev plt plan
