---
name: updatecli-compose

on:
  push:
    branches:
      - main
      - edge
  pull_request:  # TODO: remove this
    branches:
      - main
      - edge
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'  # 16:00 UTC every day

env:
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  COMMITTER_USERNAME: "updatecli[bot]"
  COMMITTER_EMAIL: "${{ github.repository_id }}+updatecli[bot]@users.noreply.forklift.run"
  FORKLIFT_VERSION: 0.8.0-alpha.2

permissions:
  contents: write
  pull-requests: write

jobs:
  forklift-pallets:
    env:
      UPDATECLI_CONFIG: .github/updatecli.d/forklift-pallets.yml
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup updatecli
        uses: updatecli/updatecli-action@v2

      - name: Setup Forklift
        uses: PlanktoScope/setup-forklift@v1
        with:
          version: ${{ env.FORKLIFT_VERSION }}

      - name: Dry-run updates
        run: "updatecli diff --config ${{ env.UPDATECLI_CONFIG }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Apply updates
        run: "updatecli apply --config ${{ env.UPDATECLI_CONFIG }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
