---
name: updatecli-forklift

on:
  push:
    branches:
      - main
      - edge
  pull_request: # TODO: delete this line after testing is done
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'  # 16:00 UTC every day

env:
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  COMMITTER_USERNAME: "updatecli[bot]"
  COMMITTER_EMAIL: "${{ github.repository_id }}+updatecli[bot]@users.noreply.forklift.run"
  FORKLIFT_VERSION: 0.8.0-alpha.3

permissions:
  contents: write
  pull-requests: write

jobs:
  forklift-pallets:
    env:
      UPDATECLI_COMPOSE: /tmp/forklift.updatecli-compose.yml
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup updatecli
        uses: updatecli/updatecli-action@v2

      - name: Setup Forklift
        uses: PlanktoScope/setup-forklift@v1
        with:
          version: ${{ env.FORKLIFT_VERSION }}

      - name: Generate updatecli compose file
        run: |
          .github/generate-forklift-updatecli-compose.sh \
            "$(pwd)" \
            ".github/forklift.updatecli-compose.yqtempl" \
            "pallets" \
            "${{ env.UPDATECLI_COMPOSE }}"

      - name: Dry-run updates
        run: CWD="$(pwd)" updatecli compose diff --file "${{ env.UPDATECLI_COMPOSE }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Apply updates
        run: CWD="$(pwd)" updatecli compose apply --file "${{ env.UPDATECLI_COMPOSE }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
